# Generated by Django 2.2.4 on 2020-07-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200704_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '칼럼'), (1, '뉴스'), (2, '소설')], default=0, verbose_name='게시글타입'),
            preserve_default=False,
        ),
    ]
