# Generated by Django 2.2.4 on 2020-07-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '메인'), (1, '이달의 주제'), (2, '선택')], verbose_name='게시글타입'),
        ),
    ]
