# Generated by Django 2.2.4 on 2020-07-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200704_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '칼럼'), (1, '뉴스'), (2, '소설')], verbose_name='게시글타입'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default/default_post_img.jpg', upload_to='posts/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업데이트시간'),
        ),
    ]
