# Generated by Django 2.2.4 on 2020-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200704_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '메인'), (1, '이달의테마'), (2, '사용자선택')], verbose_name='게시글타입'),
        ),
    ]
