# Generated by Django 3.0.8 on 2020-07-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200712_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='highlighted',
            new_name='highlight',
        ),
    ]
